<?php
add_action( 'init', 'point_register_post_type' );
function point_register_post_type() {
	$labels = [
		'name'                     => esc_html__( 'Points', 'your-textdomain' ),
		'singular_name'            => esc_html__( 'Point', 'your-textdomain' ),
		'add_new'                  => esc_html__( 'Ajouter un nouveau point', 'your-textdomain' ),
		'add_new_item'             => esc_html__( 'Ajouter un nouveau point', 'your-textdomain' ),
		'edit_item'                => esc_html__( 'éditer ce point', 'your-textdomain' ),
		'new_item'                 => esc_html__( 'Nouveau point', 'your-textdomain' ),
		'view_item'                => esc_html__( 'Voir ce point', 'your-textdomain' ),
		'view_items'               => esc_html__( 'Voir les points', 'your-textdomain' ),
		'search_items'             => esc_html__( 'Chercher dans les points', 'your-textdomain' ),
		'not_found'                => esc_html__( 'Pas de point trouvé', 'your-textdomain' ),
		'not_found_in_trash'       => esc_html__( 'Pas de point trouvé dans la corbeille', 'your-textdomain' ),
		'parent_item_colon'        => esc_html__( 'Parent point:', 'your-textdomain' ),
		'all_items'                => esc_html__( 'Tous les points', 'your-textdomain' ),
		'archives'                 => esc_html__( 'Point Archives', 'your-textdomain' ),
		'attributes'               => esc_html__( 'Point Attributes', 'your-textdomain' ),
		'insert_into_item'         => esc_html__( 'Insert into point', 'your-textdomain' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this point', 'your-textdomain' ),
		'featured_image'           => esc_html__( 'Featured image', 'your-textdomain' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'your-textdomain' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'your-textdomain' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'your-textdomain' ),
		'menu_name'                => esc_html__( 'Points', 'your-textdomain' ),
		'filter_items_list'        => esc_html__( 'Filter points list', 'your-textdomain' ),
		'filter_by_date'           => esc_html__( '', 'your-textdomain' ),
		'items_list_navigation'    => esc_html__( 'points list navigation', 'your-textdomain' ),
		'items_list'               => esc_html__( 'points list', 'your-textdomain' ),
		'item_published'           => esc_html__( 'point published', 'your-textdomain' ),
		'item_published_privately' => esc_html__( 'point published privately', 'your-textdomain' ),
		'item_reverted_to_draft'   => esc_html__( 'point reverted to draft', 'your-textdomain' ),
		'item_scheduled'           => esc_html__( 'point scheduled', 'your-textdomain' ),
		'item_updated'             => esc_html__( 'point updated', 'your-textdomain' ),
	];
	$args = [
		'label'               => esc_html__( 'Points', 'your-textdomain' ),
		'labels'              => $labels,
		'description'         => '',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => true,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'has_archive'         => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'menu_position'       => 30,
		'menu_icon'           => 'dashicons-admin-post',
		'capability_type'     => 'post',
		'supports'            => ['title', 'editor', 'thumbnail'],
		'taxonomies'          => [],
		'rewrite'             => [
			'with_front' => false,
		],
	];

	register_post_type( 'point', $args );
}