<?php
add_action( 'init', 'lien_register_post_type' );
function lien_register_post_type() {
	$labels = [
		'name'                     => esc_html__( 'Liens', 'your-textdomain' ),
		'singular_name'            => esc_html__( 'Lien', 'your-textdomain' ),
		'add_new'                  => esc_html__( 'Ajouter un nouveau lien', 'your-textdomain' ),
		'add_new_item'             => esc_html__( 'Ajouter un nouveau lien', 'your-textdomain' ),
		'edit_item'                => esc_html__( 'éditer ce lien', 'your-textdomain' ),
		'new_item'                 => esc_html__( 'Nouveau lien', 'your-textdomain' ),
		'view_item'                => esc_html__( 'Voir ce lien', 'your-textdomain' ),
		'view_items'               => esc_html__( 'Voir les liens', 'your-textdomain' ),
		'search_items'             => esc_html__( 'Chercher dans les liens', 'your-textdomain' ),
		'not_found'                => esc_html__( 'Pas de lien trouvé', 'your-textdomain' ),
		'not_found_in_trash'       => esc_html__( 'Pas de lien trouvé dans la corbeille', 'your-textdomain' ),
		'parent_item_colon'        => esc_html__( 'Parent lien:', 'your-textdomain' ),
		'all_items'                => esc_html__( 'Tous les liens', 'your-textdomain' ),
		'archives'                 => esc_html__( 'Lien Archives', 'your-textdomain' ),
		'attributes'               => esc_html__( 'Lien Attributes', 'your-textdomain' ),
		'insert_into_item'         => esc_html__( 'Insert into lien', 'your-textdomain' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this lien', 'your-textdomain' ),
		'featured_image'           => esc_html__( 'Featured image', 'your-textdomain' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'your-textdomain' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'your-textdomain' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'your-textdomain' ),
		'menu_name'                => esc_html__( 'Liens', 'your-textdomain' ),
		'filter_items_list'        => esc_html__( 'Filter liens list', 'your-textdomain' ),
		'filter_by_date'           => esc_html__( '', 'your-textdomain' ),
		'items_list_navigation'    => esc_html__( 'liens list navigation', 'your-textdomain' ),
		'items_list'               => esc_html__( 'liens list', 'your-textdomain' ),
		'item_published'           => esc_html__( 'lien published', 'your-textdomain' ),
		'item_published_privately' => esc_html__( 'lien published privately', 'your-textdomain' ),
		'item_reverted_to_draft'   => esc_html__( 'lien reverted to draft', 'your-textdomain' ),
		'item_scheduled'           => esc_html__( 'lien scheduled', 'your-textdomain' ),
		'item_updated'             => esc_html__( 'lien updated', 'your-textdomain' ),
	];
	$args = [
		'label'               => esc_html__( 'liens', 'your-textdomain' ),
		'labels'              => $labels,
		'description'         => '',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => true,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'has_archive'         => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'menu_position'       => 30,
		'menu_icon'           => 'dashicons-rest-api',
		'capability_type'     => 'post',
		'supports'            => ['title', 'editor', 'thumbnail'],
		'taxonomies'          => [],
		'rewrite'             => [
			'with_front' => false,
		],
	];

	register_post_type( 'lien', $args );
}